version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: trading-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - trading-app
    restart: unless-stopped

  trading-app:
    image: ghcr.io/yourusername/trading-system:main
    container_name: trading-app-prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - DEBUG=false
      - LOG_LEVEL=WARNING
    env_file:
      - .env.prod
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  app_data:
  app_logs: